<a href="https://colab.research.google.com/github/sushmi/machine-learning-zoomcamp/blob/main/cohorts/2025/01-intro/homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Homework #1

### Set up the environment

You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from <a href='https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/06-environment.md'>06-environment.md</a>.

In [1]:
import numpy as np
import pandas as pd

### Question 1

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

In [2]:
pd.__version__

'2.2.2'

### Getting the data

For this homework, we'll use the Car Fuel Efficiency dataset. Download it from <a href='https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'>here</a>.

You can do it with wget:
```bash
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
```
Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv


--2025-10-26 09:04:55--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.05s   

2025-10-26 09:04:55 (17.7 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [4]:
!ls

car_fuel_efficiency.csv  sample_data


In [6]:
!pwd

/content


In [7]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
# data = pd.read_csv("car_fuel_efficiency.csv")

In [8]:
data.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Question 2

How many records are in the dataset?

In [9]:
data.shape[0]

9704

### Question 3

How many fuel types are presented in the dataset?

In [10]:
data.fuel_type.nunique()

2

In [11]:
data.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

### Question 4

How many columns in the dataset have missing values?

In [12]:
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [14]:
(data.isnull().sum() > 0).sum()

np.int64(4)

### Question 5

What's the maximum fuel efficiency of cars from Asia in the dataset?

In [15]:
data.groupby('origin')['fuel_efficiency_mpg'].agg(['min', 'mean', 'max'])

min       mean        max
origin                                
Asia    6.886245  14.973830  23.759123
Europe  6.200971  14.942532  25.967222
USA     6.695483  15.040204  24.971452

In [18]:
data.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [19]:
data[data.origin == 'Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

### Question 6



1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?

In [20]:
median_screen = data['horsepower'].median()
median_screen

149.0

In [23]:
mode_screen = data['horsepower'].mode()
mode_screen

0    152.0
Name: horsepower, dtype: float64

In [24]:
data['horsepower'].fillna(mode_screen).median()

149.0



```
# This is formatted as code
```

~~Yes, it's higher~~

---


No, it's same



### Question 7

1. Select all the cars from Europe
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

In [25]:
data[data.origin == 'Europe']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
2                     170            NaN        78.0     3079.038997   
4                     210            1.0       140.0     3460.870990   
5                     190            3.0         NaN     2484.883986   
10                    230            5.0       100.0     3111.810181   
...                   ...            ...         ...             ...   
9694                  220            3.0       176.0     2837.652898   
9695                  280            5.0       154.0     3797.309878   
9696                  190            7.0        69.0     3133.329210   
9697                  220            5.0       110.0     2532.987630   
9699                  140            5.0       164.0     2981.107371   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
5             14.7        2008  Europe  Gasoline    All-wheel drive   
10            15.4        2014  Europe    Diesel    All-wheel drive   
...            ...         ...     ...       ...                ...   
9694          11.4        2013  Europe  Gasoline  Front-wheel drive   
9695          16.6        2013  Europe  Gasoline  Front-wheel drive   
9696          16.6        2008  Europe  Gasoline    All-wheel drive   
9697          14.3        2004  Europe    Diesel  Front-wheel drive   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
2           0.0            14.246341  
4           2.0            12.488369  
5          -1.0            17.271818  
10          0.0            13.386605  
...         ...                  ...  
9694       -1.0            16.233553  
9695       -1.0            10.542970  
9696        1.0            13.418128  
9697        0.0            17.305653  
9699        NaN            15.101802  

[3254 rows x 11 columns]

In [27]:
df_test = data[data.origin == 'Europe'][['vehicle_weight', 'model_year']][:7]
df_test

vehicle_weight  model_year
0      3413.433759        2003
2      3079.038997        2018
4      3460.870990        2009
5      2484.883986        2008
10     3111.810181        2014
13     2274.735191        2000
16     2673.552941        2013

In [28]:
df_test.dtypes

vehicle_weight    float64
model_year          int64
dtype: object

In [30]:
df_test.values

array([[3413.43375861, 2003.        ],
       [3079.03899737, 2018.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3111.81018139, 2014.        ],
       [2274.73519056, 2000.        ],
       [2673.55294096, 2013.        ]])

In [35]:
X = df_test.values
XTX = X.T.dot(X)
print(XTX)

XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[61289955.72540274 41191663.53461886]
 [41191663.53461886 28260843.        ]]
[[ 7.99397664e-07 -1.16516410e-06]
 [-1.16516410e-06  1.73367254e-06]]


In [36]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [37]:
w = (XTX_inv @ X.T) @ y

In [38]:
w

array([-0.07188499,  0.63097065])

In [39]:
sum(w)

np.float64(0.559085655434893)

> **Note**: we just implemented normal equation


$$w = (X^T X)^{-1} X^T y$$


We'll talk about it more in the next week (Machine Learning for Regression)